### ISSUE TITLE
Wrong s2p file generation

### ISSUE THREAD

**Issue by KobaSisyo** [NanoVNA-Saver/nanovna-saver#211]
**Describe the bug**
The S21 data in the generated s2p file appears to be S11.

**To Reproduce**
1. Output s2p file with v0.3.3.
2. Open the s2p file with v0.2.2-1.
3. S21 looks like S11.

**Expected behavior**
See S21 data.

**Screenshots**
![image](https://user-images.githubusercontent.com/55571873/86265743-2630ac00-bbff-11ea-9dcc-22d87d869dbc.png)
Green is the data acquired in v0.3.3,
Dark blue is the expected data obtained with v0.2.2-1.

**Desktop (please complete the following information):**
 - OS: Windows10 1909
 - NanoVNA-Saver version: v0.3.3

**Comment by KobaSisyo** [comment]
If you load the s2p file generated by V0.2.2-1 with v0.3.3, s2p is displayed correctly.

**Comment by zarath** [comment]
Can you supply me the s2p files? Best one saved with v0.2.2-1 and one saved with v0.3.3

**Comment by ikd-sci** [comment]
Second that. Version 0.33. 1. Load data from the examples: Files > Load as sweep > "test/data/attenuator-0643_DB.s2p"
2. Save the data as s2p: Files > Save 2-port file (S2p) > "test.s2p" 3. Load it back, S21 looks exactly like S11

Suggested fix:
NanoVNASaver.py, function exportFile, Line 591:
ts.sdata[1] = self.data21
instead of
ts.sdata[1] = self.data

**Comment by zarath** [comment]
yes, found out the same.
if able to install from source

https://github.com/zarath/nanovna-saver/tree/development

should work

**Comment by zarath** [comment]
Fixed in current Development Tree

**Comment by KobaSisyo** [comment]
This bug seems to have been fixed in pre0.3.4(Win10)!
