### ISSUE TITLE
Broken data in graphs (v035)

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#239]
It seems there is a bug in v035 graph calculations or elsewhere. Here is an example with the v034 and v035 - the same settings and connected to an H4 terminated with stock coax and stock 50ohm load (continual sweep, not calibrated).
![v034](https://user-images.githubusercontent.com/7240123/87221346-a7a8dc80-c36b-11ea-83c3-46a53e0ce666.PNG)
![v035](https://user-images.githubusercontent.com/7240123/87221351-af688100-c36b-11ea-8c4c-305e8fa94e3c.PNG)

**Comment by RandMental** [comment]
Have you Recalibrated the 0.3.5 version?     The jaggered lines normally means you need to recalibrate.  . 
-------- Original message --------From: IMO <notifications@github.com> Date: 2020/07/11  11:46  (GMT+02:00) To: NanoVNA-Saver/nanovna-saver <nanovna-saver@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [NanoVNA-Saver/nanovna-saver] Broken data in graphs (v035) (#239) 
It seems there is a bug in v035 graph calculations or elsewhere. Here is an example with the v034 and v035 - the same settings and connected to an H4 terminated with stock coax and stock 50ohm load (continual sweep, not calibrated).



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NanoVNA-Saver/nanovna-saver/issues/239",
"url": "https://github.com/NanoVNA-Saver/nanovna-saver/issues/239",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by igor-m** [comment]
The graphs are broken when "calibrated" as well - see below. The calibration has been done within saver v035.
![Calibrated v035 sweep](https://user-images.githubusercontent.com/7240123/87221811-31a67480-c36f-11ea-8c3d-a28043c9bb62.PNG)

**Comment by igor-m** [comment]
The same cal procedure with v034 and sweep
![Calibrated v034 sweep](https://user-images.githubusercontent.com/7240123/87221953-31f33f80-c370-11ea-8377-502b8ee0724f.PNG)
. Calibration has been provided within v034.

**Comment by zarath** [comment]
Very strange behaviour...
Mostly jumps at the 300/600/900/1200 MHz marks

**Comment by igor-m** [comment]
All above done with ORIGINAL FACTORY H4 firmware.
I'm going to flash the NanoVNA-H4 v0.8.4.7.dfu in..

**Comment by zarath** [comment]
@igor-m are you able to run source code installation?
It seems, that it is only happen with older sweep / scan command.
If I do a scan mask command it's looks allright.

**Comment by igor-m** [comment]
The 0847dfu works unreliably with the v305 however, it loads nonsense upon connect into start/stop and usually crashes the app. I was lucky to get the above sweep, it seems..

**Comment by igor-m** [comment]
Enclosed the debug.txt (H4-0847fw and v035 saver).
After connect it reads nonsense into STOP frequency and crashes after couple of seconds while 
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4906887/debug.txt)
doing nothing..

**Comment by zarath** [comment]
ok. crash is because of data validation... there are very high data readings. And there is a code path that then simply crashes :-(
So if data validation is disabled it should run further ...

**Comment by igor-m** [comment]
This is a "successful" start, params as above, but I OFF/ONed the H4, then started v035, the START/STOP was empty, then I connected H4, it read the H4 default START/STOP, the sweep has been done ok, but graphs with glitches (see below). Attached the debug.txt from this session..
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4906902/debug.txt)
![Sweep with v035 and 0847dfu and 2kHz bandwith 201points AFTER H4 ON_OFF](https://user-images.githubusercontent.com/7240123/87226159-4b0ce800-c392-11ea-8a9d-899078aff19e.PNG)

**Comment by igor-m** [comment]
This is as above but with Calibration (50kHz/900Mhz). Still glitches in the graphs.

[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4906929/debug.txt)
![Sweep with v035 and 0847dfu and 2kHz bandwith 201points AFTER H4 OFF_ON and CALIBRATED](https://user-images.githubusercontent.com/7240123/87226619-4a298580-c395-11ea-816f-372b6264de77.PNG)

**Comment by zarath** [comment]
can you try https://github.com/zarath/nanovna-saver/actions/runs/165679524

**Comment by igor-m** [comment]
After connecting freshly started H4 (default 50k/900M, internally calibrated) it put start/stop 27/30MHz and did a sweep.
I entered 50k/900M and did a sweep - see below (2010points). Looks promising..
![v036pre](https://user-images.githubusercontent.com/7240123/87227310-7c89b180-c39a-11ea-96d0-a96a9553d1a1.PNG)

**Comment by zarath** [comment]
So I just have to investigate which firmwares are able to do scan mask command >= 0.7.1 of original nanovna...
