### ISSUE TITLE
Value labels in R+jX chart is not always fully plotted

### ISSUE THREAD

**Issue by vreijs** [NanoVNA-Saver/nanovna-saver#426]
**Describe the bug**
The value labels in a R+jX chart is not fully printed (in this case the 'm' on the rigth side is 'abbreviated to 'n'...)

**To Reproduce**
1. Have the 'S11 R+jX' chart and make sure that the right axis's 'jX' 'Data axis' Fixed span' is like 'Minimum jX' -0.25 and 'Maximum jX' +0.25
2. The 0.25 is shown as '250n' in the chart (I think the rest of the 'm' is outside the plot area). 
3. The same is shown when 'Popout chart' is used (even if that window is maximased)

**Expected behavior**
That it shows the full 'm' (and perhaps other deminsensions)

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Python version: [if applicable] n/a
 - NanoVNA-Saver version: [e.g. 0.1.4] 0.3.9
![missing-m-on-the-right-axis](https://user-images.githubusercontent.com/17218070/131196901-7f56b385-122a-4485-8594-dfc7e2382bb3.gif)

**Additional context**

**Comment by rjordans** [comment]
I can confirm this problem and had a quick look.  It seems that this is something that happens in Charts/RI.py and that there are two options for fixing it.

Option 1:
- Reduce the precision at which the numbers are printed here, currently the chart has 4 digit precision and going for 3 digits makes things fit again. Changing the code below to use a 3 digit format fixes the problem for me.

https://github.com/NanoVNA-Saver/nanovna-saver/blob/e112f255612527815ba26470468dc34da6730cf3/NanoVNASaver/Charts/RI.py#L233

Option 2:
- Increase the reserved space so that the longer labels fit.  If I change the code below to reserve 55 pixels as rightMargin it also works. This does reduce the effective width of the graph on smaller screens though.

https://github.com/NanoVNA-Saver/nanovna-saver/blob/e112f255612527815ba26470468dc34da6730cf3/NanoVNASaver/Charts/RI.py#L40

I'm not sure which of both options I would prefer, I'm tempted to vote for option 1 though.

Anyone here who has a preference?
