### ISSUE TITLE
Crash on Apply port 1 calibration using Calibration Assistant

### ISSUE THREAD

**Issue by good-point-lab** [NanoVNA-Saver/nanovna-saver#546]
**Describe the bug**
The app repeatedly crashes when selecting Apply option after port 1 calibration using Calibration Assitant

**To Reproduce**
1. Select calibration and use calibration assistant
2. Perform 3 calibration steps on port 1 (open, closed, load)
3. In the 'Yes' or 'Apply' dialog select 'Apply'
4. The saver crashes each time.

**Expected behavior**
Expected to be back to the calibration screen and to be able to save the calibration parameters

**Screenshots**
Nothing to show after the crash.  The crash report that I sent to Apple is attached.

**Desktop (please complete the following information):**
 - OS: OSX 12.6. Mac Air M1
 - Python version: using binary 
 - NanoVNA-Saver version: 0.5.2

**Additional context**
A very useful application, but please do more testing...the release feels pretty fragile...
[report.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/9568356/report.txt)

**Comment by zarath** [comment]
Can you start nanovna-saver with the -d option an post the debug output?

I cannot do anything with the mac debug output.
If possible could you try the https://github.com/zarath/nanovna-saver/tree/bugfix/541_crash_in_ri branch ?

Many crashes are caused by changes of python to 3.10 and newer PyQt libs. In previous versions it was ok to call QPoint, QRect .. etc with a float as position value, now it has to be casted to int....

**Comment by good-point-lab** [comment]
Hi Holger. Thank you for looking into the problem.  I can not reproduce it this morning... yesterday the crash was 100% reproducible the way I described it above.  I have just run the app with -d and without, no problem.  I suspect XCode update that might happen overnight.  In any case, I will keep an eye on it and will report my observations.

**Comment by zarath** [comment]
The problem with testing is, that I only have limited hard-/software resources. And especially UI tests are hard to automate.
For example older Python and Qt versions silently casts float to int when needed, but current just crash with a traceback...

I try to get as most of non UI code, like calculations, out of the Qt code parts, to do automated unit tests to ensure that at least calculations are stable and fully tested.

regards
  Holger

**Comment by good-point-lab** [comment]
Hi Holger,
I understand and I am aware of the latest Python casting requirements from
my previous projects.  If I have more time I would look closer...  At this
point, I will continue using the Saver in debug mode and if I will see
anything strange, I will post it on the Saver GitHub pages.  I plan to
actively use NanoVNA and as its tiny UI is rather inconvenient, I depend on
the Saver.
Best,
Alex

Boston, USA

**Comment by zarath** [comment]
That Python 3.10 external library problems caught me off guard.
And regarding testing, unluckily I got really low feedback on trunk versions from the ham community.
Many users aren't firm with pull request or even attaching dumps to the error reports here ...
So you are a notable exception.

I know, I should write also a contribution and error reporting / debugging guide. At least, with debug mode and traceback i can hunt most of the issues.
Is #545 also gone? - I know that the sweeper task should also be more robust - and proper data packages should be transfered instead of strings between hardware modules and sweeper...

**Comment by good-point-lab** [comment]
Hi Holger,
I will try 545 again (after I switched to binary 0.5.2 and it worked, I
removed 0.4).  On a general note, in my recent project, I had a lot of
compatibility problems with 3.10 on the new OSX/M1.  Only a very narrow
combination of the compiled dependencies worked that confirms your point -
we have to be very careful with the new Python, oh well...

- Alex

**Comment by zarath** [comment]
seems to be fixed
